
from typing import Protocol, runtime_checkable

@runtime_checkable
class Digest(Protocol):
    def __new__(self) -> None:...
    def new_with_prefix(data : bytes) -> "Digest":...
    def update(self, data : bytes) -> None:...
    def finalize(self) -> bytes:...
    def finalize_reset(self) -> bytes:...
    def reset(self) -> None:...
    @staticmethod
    def output_size() -> int:...
    @staticmethod
    def digest(data : bytes):...
    def name(self) -> str:...
    def __setattr__(self, name: str, value) -> None:...
    def __delattr__(self, name: str) -> None:...
    def __repr__(self) -> str:...
    def __str__(self) -> str:...
