name: Rust Release

env:
  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

on:
  push:
    tags:
      - rs-v*
      - v*

jobs:
  rust_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Dry Run Publish package rust
        working-directory: ./bintensors
        run: cargo publish --dry-run

      - name: Publish package rust
        if: ${{ !contains(github.ref, 'rc') }}
        working-directory: ./bintensors
        run: cargo publish --token ${CRATES_TOKEN}
