name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain: [stable]
        include:
          - os: ubuntu-latest
            toolchain: "1.74"
    defaults:
      run:
        working-directory: mrkle

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Build
        run: cargo build --all-targets --verbose

      - name: Lint with Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run Tests
        run: cargo test --verbose

      - name: Run No-STD Tests
        run: cargo test --no-default-features --features alloc --verbose
